-- Отключаем проверку внешних ключей, чтобы безболезненно очистить базу
SET REFERENTIAL_INTEGRITY FALSE;

-- Удаляем таблицы в обратном порядке
DROP TABLE IF EXISTS post_tags;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS post;

SET REFERENTIAL_INTEGRITY TRUE;

-- 1. Таблица Постов
CREATE TABLE post (
                      idpost INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(45) NOT NULL,
                      text VARCHAR(2000) NOT NULL,
                      likes_count INT NOT NULL DEFAULT 0,
                      created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Уникальный индекс для заголовка
CREATE UNIQUE INDEX title_UNIQUE ON post (title);


-- 2. Таблица Комментариев
CREATE TABLE comment (
                         idcomment INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         text VARCHAR(255) NOT NULL,
                         idpost INT NOT NULL,
                         CONSTRAINT fk_comment_post
                             FOREIGN KEY (idpost)
                                 REFERENCES post (idpost)
                                 ON DELETE CASCADE
                                 ON UPDATE CASCADE
);

-- Индекс для внешнего ключа
CREATE INDEX comment_post_idx ON comment (idpost);


-- 3. Таблица Тегов
CREATE TABLE tag (
                     idtag INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     tag_name VARCHAR(45) NOT NULL UNIQUE
);

-- Уникальный индекс для имени тега
CREATE UNIQUE INDEX tag_name_UNIQUE ON tag (tag_name);


-- 4. Связующая таблица (Посты - Теги)
CREATE TABLE post_tags (
                           idpost_tags INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           idpost INT NOT NULL,
                           idtag INT NOT NULL,
                           CONSTRAINT fk_posttag_post
                               FOREIGN KEY (idpost)
                                   REFERENCES post (idpost)
                                   ON DELETE CASCADE
                                   ON UPDATE CASCADE,
                           CONSTRAINT fk_posttag_tag
                               FOREIGN KEY (idtag)
                                   REFERENCES tag (idtag)
                                   ON DELETE CASCADE
                                   ON UPDATE CASCADE
);

-- Индексы для связей
CREATE INDEX posttag_post_idx ON post_tags (idpost);
CREATE INDEX posttag_tag_idx ON post_tags (idtag);
