jakarta.persistence.jdbc.url=${DB_URL}
jakarta.persistence.jdbc.user=${DB_USER}
jakarta.persistence.jdbc.password=${DB_PASSWORD}

hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true